version: "3.9"

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/pleaseletmein
      - NEO4J_PLUGINS=["apoc"]
    networks:
      - promethai_mem_backend

  promethai_mem:
    networks:
      - promethai_mem_backend
    build:
      context: ./
    volumes:
      - "./:/app"
      - ./.data:/app/.data

    environment:
      - HOST=0.0.0.0
    profiles: ["exclude-from-up"]
    ports:
      - 8000:8000
      - 443:443
      - 80:80
      - 50051:50051
    depends_on:
      - postgres
      - neo4j
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 8GB


  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=bla
      - POSTGRES_PASSWORD=bla
      - POSTGRES_DB=bubu
    networks:
      - promethai_mem_backend
    ports:
      - "5432:5432"

#  superset:
#    platform: linux/amd64
#    build:
#      context: ./superset
#      dockerfile: Dockerfile
#    container_name: superset
#    environment:
#      - ADMIN_USERNAME=admin
#      - ADMIN_EMAIL=vasilije@topoteretes.com
#      - ADMIN_PASSWORD=admin
#      - POSTGRES_USER=bla
#      - POSTGRES_PASSWORD=bla
#      - POSTGRES_DB=bubu
#    networks:
#      - promethai_mem_backend
#    ports:
#      - '8088:8088'
#    depends_on:
#      - postgres

networks:
  promethai_mem_backend:
    name: promethai_mem_backend

